insert into users_allowed (email, firstname, lastname, position) values (LOWER('pablo.lamo@adidas-group.com'), 'Pablo', 'Lamo', 'GM Argentina'),
(LOWER('mariacecilia.yad@adidas.com '), 'Maria Cecilia ', 'Yad ', 'Sr. Director Finance'),
(LOWER('anabel.papouchado@adidas.com'), 'Anabel', 'Papouchado', 'Sr. Director SCM'),
(LOWER('francisco.morello@adidas.com'), 'Francisco', 'Morello', 'Sr Manager Legal & Compliance'),
(LOWER('fernando.colombo@adidas-group.com'), 'Fernando ', 'Colombo', 'Sr Director Brand Activation adidas'),
(LOWER('juliet.aragones@adidas.com'), 'Juliet ', 'Aragones', 'Sr. Director DTC'),
(LOWER('fernanda.gazal@adidas.com'), 'Fernanda ', 'Gazal', 'Sr. Director Human Resources'),
(LOWER('mariafernanda.capilla@adidas.com'), 'María Fernanda', 'Capilla', 'Director IT'),
(LOWER('federico.borsani@adidas.com'), 'Federico', 'Borsani', 'Sr. Director Sales'),
(LOWER('andrea.pellicani@adidas.com'), 'Andrea', 'Pellicani', 'Director Business Development'),
(LOWER('santiago.morenohueyo@adidas.com'), 'Santiago', 'Moreno Hueyo', 'Director Country Affairs'),
(LOWER('olivier.gianina@adidas.com'), 'Olivier', 'Gianina', 'GM Brazil'),
(LOWER('Pedro.Mello@adidas.com'), 'Mello', 'Pedro', 'Director Business Development'),
(LOWER('daniela.valsani@adidas.com'), 'Daniela', 'Valsani', 'Sr. Director Brand Activation'),
(LOWER('diogo.figueiredo@adidas-group.com'), 'Diogo ', 'Figueiredo', 'Sr. Director SCM'),
(LOWER('jane.jose@adidas.com'), 'Jane ', 'Jose ', 'Director IT'),
(LOWER('federico.balducci@adidas-group.com'), 'Federico', 'Balducci ', 'Director Operations Mngmt FTW'),
(LOWER('fernando.shimizu@adidas-group.com'), 'Fernando', 'Shimizu', 'Senior Director Finance'),
(LOWER('carla.salvador@adidas.com'), 'Carla ', 'Salvador ', 'Sr. Director Sales'),
(LOWER('silene.rodrigues@adidas.com'), 'Silene', 'Rodrigues', 'Senior HR Director'),
(LOWER('joao.meyer@adidas.com'), 'Joao ', 'Meyer', 'Sr. Director DTC'),
(LOWER('jerome.leveque@adidas.com'), 'Jerome ', 'Leveque', 'GM Chile'),
(LOWER('alejandro.chahud@adidas.com'), 'Alejandro', 'Chahud', 'Sr. Director DTC'),
(LOWER('cristian.correa@adidas.com'), 'Cristian ', 'Correa', 'Sr. Director Sales'),
(LOWER('pablo.cavallaro@adidas.com'), 'Pablo', 'Cavallaro', 'Sr. Director Brand Activation (adidas)'),
(LOWER('xavier.espinosa@adidas.com'), 'Xavier ', 'Espinosa', 'Director Business Development'),
(LOWER('margaret.hirsch@adidas-group.com'), 'Margaret', 'Hirsch', 'Director Legal & Compliance'),
(LOWER('maria.elena.alarcon@adidas-group.com'), 'Maria Elena ', 'Alarcon', 'Director Finance'),
(LOWER('irene.schlechter@adidas.com'), 'Irene', 'Schlechter', 'Director Human Resources'),
(LOWER('shyon.endara@adidas-group.com'), 'Shyon', 'Endara', 'Sr. Director SCM'),
(LOWER('Markus.Morent@adidas-group.com'), 'Markus', 'Morent', 'GM Colombia'),
(LOWER('liz.monroy@adidas.com'), 'Liz', 'Monroy', 'Director HR'),
(LOWER('veronica.roldan@adidas.com'), 'Veronica ', 'Roldan', 'Director SCM'),
(LOWER('juan.motta@adidas-group.com'), 'Juan', 'Motta', 'Director Brand Activation (adidas)'),
(LOWER('rakesh.joshi@adidas-group.com'), 'Rakesh', 'Joshi', 'Sr. Director DTC'),
(LOWER('carolina.martinez@adidas.com'), 'Carolina ', 'Martinez', 'Director Business Development'),
(LOWER('sergio.pinzon@adidas.com'), 'Sergio', 'Pinzon', 'Director Finance'),
(LOWER('antonio.justino@adidas.com'), 'Antonio', 'Justino', 'Director IT Management'),
(LOWER('janice.cruzalegui@adidas.com'), 'Janice', 'Cruzalegui L', 'Director Sales'),
(LOWER('anaximena.diaz@adidas-group.com'), 'Ana Ximena', 'Diaz', 'Director Legal & Compliance'),
(LOWER('jorge.dionne@adidas-group.com'), 'Jorge', 'Dionne', 'GM Mexico'),
(LOWER('ericka.meixueiro@adidas-group.com'), 'Ericka', 'Meixueiro', 'Director Legal & Compliance'),
(LOWER('mariasilvia.saba@adidas.com'), 'Maria Silvia', 'Saba', 'IT Director'),
(LOWER('sergio.flores@adidas-group.com'), 'Sergio', 'Flores', 'Director DTC'),
(LOWER('bruno.yoshida@adidas.com'), 'Bruno', 'Yoshida', 'Sr. Director Sales'),
(LOWER('andres.rubio@adidas.com'), 'Andrés', 'Rubio', 'Director Business Development'),
(LOWER('carlos.osorio@adidas-group.com'), 'Carlos', 'Osorio', 'Director Key City'),
(LOWER('miguel.jimenez@adidas.com'), 'Miguel', 'Jiménez', 'Sr. Director SCM'),
(LOWER('graziela.schultz@adidas.com'), 'Graziela ', 'Schultz', 'Sr. Director Finance'),
(LOWER('mariana.coronado@adidas-group.com'), 'Mariana ', 'Coronado', 'Director Human Resources'),
(LOWER('ana.fernandez@adidas.com'), 'Ana Belen ', 'Fernandez', 'Sr Director Brand Activation (adidas)'),
(LOWER('raul.marcenaro@adidas.com'), 'Raul', 'Marcenaro', 'GM Peru'),
(LOWER('guillermo.byrne@adidas.com'), 'Guillermo', 'Byrne', 'Director Brand Activation (adidas)  '),
(LOWER('cecilia.pomar@adidas-group.com'), 'Cecilia ', 'Pomar', 'Director Human Resources'),
(LOWER('eduardo.ticeran@adidas.com'), 'Eduardo', 'Ticeran', 'Sr. Manager Legal & Compliance'),
(LOWER('gonzalo.delarosatoro@adidas-group.com'), 'Gonzalo', 'De la Rosa Toro', 'Director SCM'),
(LOWER('alvaro.taboada@adidas.com'), 'Alvaro ', 'Taboada', 'Sr. Director Sales'),
(LOWER('mayte.velaochaga@adidas.com'), 'Mayte', 'Velaochaga', 'Director Business Development'),
(LOWER('julio.nunez@adidas.com'), 'Julio', 'Nunez', 'Director Finance'),
(LOWER('claudia.tricerri@adidas.com'), 'Claudia ', 'Tricerri M', 'Director DTC'),
(LOWER('salvador.mothe@adidas-group.com'), 'Salvador', 'Mothe', 'Sr. Director Commercial CAC'),
(LOWER('rosana.duran@adidas.com'), 'Rosana', 'Duran', 'Finance Director CAC '),
(LOWER('juanjose.roque@adidas.com'), 'Juan Jose ', 'Roque', 'Director Commercial '),
(LOWER('fabio.strutz@adidas.com'), 'Fabio ', 'Strutz', 'Sr. Manager Digital'),
(LOWER('luz.garzon@adidas.com'), 'Luz ', 'Garzon', 'Director SCM'),
(LOWER('edwin.zapata@adidas-group.com'), 'Edwin ', 'Zapata', 'Director Legal & Compliance'),
(LOWER('leslie.lushman@adidas.com'), 'Leslie', 'Lushman', 'Director Business Development'),
(LOWER('mariacarolina.vega@adidas.com'), 'MariaCarolina', 'Vega', 'Sr. Manager HR'),
(LOWER('flavia.bittencourt@adidas.com'), 'Flavia', 'Bittencourt', 'Managing Director'),
(LOWER('bas.van.dorp@adidas.com'), 'Bas', 'Van Dorp', 'VP adidas Brand'),
(LOWER('iza.restom@adidas.com'), 'Iza ', 'Restom', 'Sr. Director Training & Core Apparel'),
(LOWER('fidel.gonzalez@adidas.com'), 'Jesus Fidel', 'Gonzalez', 'Sr. Director CTC Merchandising'),
(LOWER('nathan.colopy@adidas-group.com'), 'Nathan', 'Colopy', 'Sr. Director Running & Core Footwear'),
(LOWER('sara.camargo@adidas.com'), 'Sara', 'Camargo', 'Director Marketing Operations'),
(LOWER('paulo.ziliotto@adidas.com'), 'Paulo', 'Ziliotto', 'Sr. Director Newsroom'),
(LOWER('juan.ignacio.arrieta@adidas.com'), 'Juan Ignacio ', 'Arrieta ', 'Director HBS/BB/Out'),
(LOWER('tristan.merkaert@adidas.com'), 'Tristan', 'Merkaert', 'Sr. Director Originals'),
(LOWER('renier.benson@adidas-group.com'), 'Renier', 'Benson', 'Director Rewards'),
(LOWER('cecilia.nascimento@adidas.com'), 'Cecilia ', 'Nascimento ', 'Sr. Manager HR Initiative'),
(LOWER('daniza.nunez@adidas.com'), 'Daniza', 'Nuñez', 'Sr. Director Human Resources'),
(LOWER('Sabrina.Cruz@adidas.com'), 'Sabrina', 'Cruz', 'Director Talent'),
(LOWER('doyna.bordanea@adidas.com'), 'Doyna', 'Bordanea', 'Sr. Manager Workplace Management'),
(LOWER('Angelica.Velandia@adidas.com'), 'Angelica', 'Velandia', 'Director HR Services LAM'),
(LOWER('odette.beattie@adidas.com'), 'Odette', 'Beattie ', 'Director Talent Acquisition'),
(LOWER('michael.slofstra@adidas.com'), 'Michael', 'Slofstra', 'VP Finance'),
(LOWER('Michael.Sadowskij@adidas.com'), 'Michael', 'Sadowskij', 'Director Non Trade Procurement'),
(LOWER('martin.chiappe@adidas.com'), 'Martin', 'Chiappe', 'Director DP'),
(LOWER('Edward.Ostojich@adidas.com'), 'Edward', 'Ostojich', 'Sr. Director FP&A'),
(LOWER('eric.levert@adidas.com'), 'Eric', 'Levert', 'DirectorTax'),
(LOWER('sofia.becerra@adidas.com'), 'Sofia', 'Becerra', 'Director IC PP'),
(LOWER('javier.vela@adidas-group.com'), 'Javier ', 'Vela', 'VP SCM'),
(LOWER('guido.giovannucci@adidas.com'), 'Guido', 'Giovannucci', 'Sr. Director Purchasing'),
(LOWER('melanie.de.leon@adidas-group.com'), 'Melanie', 'De Leon', 'Director Logistics'),
(LOWER('javier.julia@adidas-group.com'), 'Javier ', 'Julia', 'Director Franchise Operations'),
(LOWER('rohit.kumar2@adidas.com'), 'Rohit ', 'Kumar', 'Director Buying & Trading'),
(LOWER('karin.hugger@adidas-group.com'), 'Karin', 'Hugger', 'Director Store Development & Real Estate'),
(LOWER('julien.vassalini@adidas-group.com'), 'Julien', 'Vassalini', 'VP Digital'),
(LOWER('Alejandro.Warnken@adidas-group.com'), 'Alejandro ', 'Warnken', 'Director Digital Operations'),
(LOWER('juan.carlos.osorio.ortiz@adidas.com'), 'Juan Carlos ', 'Osorio', 'Director Digital Analytics'),
(LOWER('Jonatan.Ospina@adidas.com'), 'Jonatan ', 'Ospina', 'Sr. Manager Program Delivery'),
(LOWER('danilo.casarin@adidas.com'), 'Danilo', 'Casarin', 'Sr. Director IT'),
(LOWER('giselle.velarde@adidas-group.com'), 'Giselle', 'Velarde', 'Director Business Intelligence '),
(LOWER('alfredo.molina@adidas.com'), 'Alfredo ', 'Molina', 'Sr. Manager Business Solutions'),
(LOWER('ken.leon@adidas-group.com'), 'Ken', 'Leon', 'Director IT Management'),
(LOWER('marcelo.pereira@adidas.com'), 'Marcelo', 'Pereira', 'Director Service Management'),
(LOWER('alexander.mejia@adidas.com'), 'Alexander', 'Mejia', 'Director Projects and Programs'),
(LOWER('javier.landa@adidas-group.com'), 'Javier ', 'Landa', 'VP Wholesale'),
(LOWER('fernando.arruk@adidas.com'), 'Fernando', 'Arruk', 'Director Sales Development KAM'),
(LOWER('lelia.andeol@adidas.com'), 'Lelia', 'Andeol ', 'Director Customer Service '),
(LOWER('fernando.testa@adidas.com'), 'Fernando', 'Testa', 'Sr. Manager Digital Wholesale Solutions'),
(LOWER('genoveva.wong@reebok.com'), 'Wong', 'Genoveva', 'Director DPC'),
(LOWER('marlene.muhlbacher@adidas.com'), 'Marlene', 'Muhlbacher', 'Sr. Director Business Development'),
(LOWER('alvaro.rodriguez@adidas.com'), 'Alvaro ', 'Rodriguez', 'Director Strategy Execution'),
(LOWER('bianca.plag@adidas.com'), 'Bianca ', 'Plag', 'Senior Manager Strategy Planning'),
(LOWER('alvaro.olavarria@adidas.com'), 'Alvaro ', 'Olavarria', 'Director Sustainability'),
(LOWER('kadine.hurtado@adidas-group.com'), 'Kadine', 'Hurtado', 'VP Legal'),
(LOWER('Felipe.Savone@adidas.com'), 'Felipe', 'Savone', 'Managing Editor LAM'),
(LOWER('Jacqueline.Mcleod@adidas.com'), 'Jacqueline', 'Mcleod', 'Manager Strategy Planning'),
(LOWER('Andres.Olaya@adidas.com'), 'Andres ', 'Olaya', 'Executive Assistant'),
(LOWER('Valentina.Gonzalez@adidas.com'), 'Valentina', 'Gonzalez', 'Manager Internal Comms'),
(LOWER('Cesibel.Castillo@adidas.com'), 'Cesibel', 'Castillo', 'Sr. Manager Strategy Execution'),
(LOWER('Gabriela.Velazquez@adidas.com'), 'Gabriela', 'Velazquez', 'Manager NTP'),
(LOWER('sebastian.gonzalez@piknik.com.mx'), 'Sebastian', 'Gonzalez', 'Piknik'),
(LOWER('elisa.moreno@piknik.com.mx'), 'Elisa', 'Moreno', 'Piknik'),
(LOWER('fernada.broca@piknik.com.mx'), 'Fernanda ', 'Broca', 'Piknik'),
(LOWER('gustavo.jordan@piknik.com.mx'), 'Gustavo', 'Jordán', 'Piknik'),
(LOWER('braulio.gaytan@piknik.com.mx '), 'Braulio', 'Gaytán', 'Piknik'),
(LOWER('paola.llaguno@piknik.com.mx'), 'Paola', 'Llaguno', 'Piknik'),
(LOWER('jonathan.torres@piknik.com.mx '), 'Jonathan', 'Torres', 'Piknik'),
(LOWER('barbara.torres@piknik.com.mx '), 'Barbara ', 'Torres', 'Piknik'),
(LOWER('piknikprojectattak@gmail.com '), 'Extra', 'Extra', 'Piknik');